/** @type {import('next-sitemap').IConfig} */
module.exports = {
    siteUrl: process.env.SITE_URL || 'https://finderight.com',
    generateRobotsTxt: true,
    generateIndexSitemap: true,
    sitemapSize: 5000,
    
    // Automatically set priority and change frequency based on the path
    transform: async (config, path) => {
        // High priority for the homepage
        if (path === '/') {
            return {
                loc: path,
                changefreq: 'always',
                priority: 1.0,
                lastmod: new Date().toISOString(),
            }
        }
        
        // High priority and frequent changes for main category hubs
        if (path.match(/^\/(jobs|study-news|result|admit-card|answer-key|admission|documents)$/)) {
            return {
                loc: path,
                changefreq: 'hourly',
                priority: 0.9,
                lastmod: new Date().toISOString(),
            }
        }

        // Default settings for other static pages (like /about, /contact)
        return {
            loc: path,
            changefreq: config.changefreq,
            priority: config.priority,
            lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
        }
    },

    exclude: [
        '/admin',
        '/admin/*',
        '/dashboard',
        '/dashboard/*',
        '/profile',
        '/login',
        '/signup',
        '/search',
        '/api/*', // Ensure API routes aren't accidentally indexed
        '/server-sitemap.xml',
    ],

    // Include the dynamic sitemap generated by Next.js for your dynamic posts
    robotsTxtOptions: {
        policies: [
            {
                userAgent: '*',
                allow: '/',
                disallow: [
                    '/admin',
                    '/admin/*',
                    '/dashboard',
                    '/dashboard/*',
                    '/profile',
                    '/login',
                    '/signup',
                    '/search',
                    '/api/',
                    '/*?*', // Disallow URLs with query parameters to prevent duplicate content indexing
                ],
            },
            // Specific rules to allow Googlebot and Googlebot-News explicitly
            {
                userAgent: 'Googlebot',
                allow: '/',
            },
            {
                userAgent: 'Googlebot-News',
                allow: '/',
            }
        ],
        additionalSitemaps: [
            'https://finderight.com/server-sitemap.xml', // Ensure this URL actually outputs valid XML
        ],
    },
};